version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./peat_data.db:/app/peat_data.db
    env_file:
      - .env
    restart: unless-stopped
